name = "r2-admin"
main = "src/index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[r2_buckets]]
binding = "B_r2_mkqnsvkt"
bucket_name = "r2-mkqnsvkt"

[[r2_buckets]]
binding = "B_r2_mkr223gr"
bucket_name = "r2-mkr223gr"

[[r2_buckets]]
binding = "B_r2_mkr2bjl3"
bucket_name = "r2-mkr2bjl3"

[[r2_buckets]]
binding = "B_r2_mkr2c3j7"
bucket_name = "r2-mkr2c3j7"

