name = "test"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "file-1769088855508-974617971.js"

[[kv_namespaces]]
binding = "KV"
id = "kv-mkphy1x3"

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "d1-mkphy467"

[vars]
ADMIN_PASSWORDS = ["Qawsed2.."]
DOMAINS = ["upig.qzz.io"]
ENABLE_USER_CREATE_EMAIL = "true"
ENABLE_USER_DELETE_EMAIL = "true"
JWT_SECRET = "a068e3b2150b144044d15cbcfea714d4a5134499d9e328e9dfe7ce0dd8e5023e"

[dev]
port = 8000
ip = "0.0.0.0"